// <auto-generated />
using System;
using KutuphaneApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212065402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KutuphaneApi.Models.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KopyaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SonIadeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KopyaId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsbnNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsbnNo")
                        .IsUnique();

                    b.HasIndex("TurId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.KitapKopya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RafKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.ToTable("KitapKopyalar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.KitapYazar", b =>
                {
                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YazarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KitapId", "YazarId");

                    b.HasIndex("YazarId");

                    b.ToTable("KitapYazarlar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OgrNo")
                        .IsUnique();

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Tur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Turler");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("YazarAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YazarSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Islem", b =>
                {
                    b.HasOne("KutuphaneApi.Models.KitapKopya", "Kopya")
                        .WithMany("Islemler")
                        .HasForeignKey("KopyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneApi.Models.Ogrenci", "Ogrenci")
                        .WithMany("Islemler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kopya");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Kitap", b =>
                {
                    b.HasOne("KutuphaneApi.Models.Tur", "Tur")
                        .WithMany("Kitaplar")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("KutuphaneApi.Models.KitapKopya", b =>
                {
                    b.HasOne("KutuphaneApi.Models.Kitap", "Kitap")
                        .WithMany("Kopyalar")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");
                });

            modelBuilder.Entity("KutuphaneApi.Models.KitapYazar", b =>
                {
                    b.HasOne("KutuphaneApi.Models.Kitap", "Kitap")
                        .WithMany("KitapYazarlar")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneApi.Models.Yazar", "Yazar")
                        .WithMany("KitapYazarlar")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Kitap", b =>
                {
                    b.Navigation("KitapYazarlar");

                    b.Navigation("Kopyalar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.KitapKopya", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Ogrenci", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Tur", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("KutuphaneApi.Models.Yazar", b =>
                {
                    b.Navigation("KitapYazarlar");
                });
#pragma warning restore 612, 618
        }
    }
}
